/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as N3LaunchRouteImport } from './routes/n3-launch'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs.index'
import { Route as AdminDevN3ConnectRouteImport } from './routes/admin.dev.n3-connect'
import { Route as AdminDevBootstrapRouteImport } from './routes/admin.dev.bootstrap'
import { Route as AuthenticatedJobsQuickRouteImport } from './routes/_authenticated/jobs.quick'
import { Route as AuthenticatedJobsNewRouteImport } from './routes/_authenticated/jobs.new'
import { Route as AuthenticatedJobsJobIdRouteImport } from './routes/_authenticated/jobs.$jobId'
import { Route as AuthenticatedAdminDevRouteRouteImport } from './routes/_authenticated/admin/dev/route'
import { Route as ApiPublicHooksSyncTickRouteImport } from './routes/api/public/hooks/sync-tick'
import { Route as AuthenticatedJobsCreatedIdRouteImport } from './routes/_authenticated/jobs.created.$id'
import { Route as AuthenticatedAdminDevSyncRouteImport } from './routes/_authenticated/admin/dev/sync'
import { Route as AuthenticatedAdminDevStatusRouteImport } from './routes/_authenticated/admin/dev/status'
import { Route as AuthenticatedAdminDevStatusApiRouteImport } from './routes/_authenticated/admin/dev/status.api'

const N3LaunchRoute = N3LaunchRouteImport.update({
  id: '/n3-launch',
  path: '/n3-launch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminDevN3ConnectRoute = AdminDevN3ConnectRouteImport.update({
  id: '/admin/dev/n3-connect',
  path: '/admin/dev/n3-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDevBootstrapRoute = AdminDevBootstrapRouteImport.update({
  id: '/admin/dev/bootstrap',
  path: '/admin/dev/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJobsQuickRoute = AuthenticatedJobsQuickRouteImport.update({
  id: '/jobs/quick',
  path: '/jobs/quick',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsNewRoute = AuthenticatedJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsJobIdRoute = AuthenticatedJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDevRouteRoute =
  AuthenticatedAdminDevRouteRouteImport.update({
    id: '/admin/dev',
    path: '/admin/dev',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksSyncTickRoute = ApiPublicHooksSyncTickRouteImport.update({
  id: '/api/public/hooks/sync-tick',
  path: '/api/public/hooks/sync-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJobsCreatedIdRoute =
  AuthenticatedJobsCreatedIdRouteImport.update({
    id: '/jobs/created/$id',
    path: '/jobs/created/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDevSyncRoute =
  AuthenticatedAdminDevSyncRouteImport.update({
    id: '/sync',
    path: '/sync',
    getParentRoute: () => AuthenticatedAdminDevRouteRoute,
  } as any)
const AuthenticatedAdminDevStatusRoute =
  AuthenticatedAdminDevStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => AuthenticatedAdminDevRouteRoute,
  } as any)
const AuthenticatedAdminDevStatusApiRoute =
  AuthenticatedAdminDevStatusApiRouteImport.update({
    id: '/api',
    path: '/api',
    getParentRoute: () => AuthenticatedAdminDevStatusRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/n3-launch': typeof N3LaunchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/admin/dev': typeof AuthenticatedAdminDevRouteRouteWithChildren
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/jobs/quick': typeof AuthenticatedJobsQuickRoute
  '/admin/dev/bootstrap': typeof AdminDevBootstrapRoute
  '/admin/dev/n3-connect': typeof AdminDevN3ConnectRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/admin/dev/status': typeof AuthenticatedAdminDevStatusRouteWithChildren
  '/admin/dev/sync': typeof AuthenticatedAdminDevSyncRoute
  '/jobs/created/$id': typeof AuthenticatedJobsCreatedIdRoute
  '/api/public/hooks/sync-tick': typeof ApiPublicHooksSyncTickRoute
  '/admin/dev/status/api': typeof AuthenticatedAdminDevStatusApiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/n3-launch': typeof N3LaunchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/admin/dev': typeof AuthenticatedAdminDevRouteRouteWithChildren
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/jobs/quick': typeof AuthenticatedJobsQuickRoute
  '/admin/dev/bootstrap': typeof AdminDevBootstrapRoute
  '/admin/dev/n3-connect': typeof AdminDevN3ConnectRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/admin/dev/status': typeof AuthenticatedAdminDevStatusRouteWithChildren
  '/admin/dev/sync': typeof AuthenticatedAdminDevSyncRoute
  '/jobs/created/$id': typeof AuthenticatedJobsCreatedIdRoute
  '/api/public/hooks/sync-tick': typeof ApiPublicHooksSyncTickRoute
  '/admin/dev/status/api': typeof AuthenticatedAdminDevStatusApiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/n3-launch': typeof N3LaunchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/admin/dev': typeof AuthenticatedAdminDevRouteRouteWithChildren
  '/_authenticated/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/_authenticated/jobs/new': typeof AuthenticatedJobsNewRoute
  '/_authenticated/jobs/quick': typeof AuthenticatedJobsQuickRoute
  '/admin/dev/bootstrap': typeof AdminDevBootstrapRoute
  '/admin/dev/n3-connect': typeof AdminDevN3ConnectRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/admin/dev/status': typeof AuthenticatedAdminDevStatusRouteWithChildren
  '/_authenticated/admin/dev/sync': typeof AuthenticatedAdminDevSyncRoute
  '/_authenticated/jobs/created/$id': typeof AuthenticatedJobsCreatedIdRoute
  '/api/public/hooks/sync-tick': typeof ApiPublicHooksSyncTickRoute
  '/_authenticated/admin/dev/status/api': typeof AuthenticatedAdminDevStatusApiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/n3-launch'
    | '/settings'
    | '/support'
    | '/admin/dev'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/jobs/quick'
    | '/admin/dev/bootstrap'
    | '/admin/dev/n3-connect'
    | '/jobs/'
    | '/admin/dev/status'
    | '/admin/dev/sync'
    | '/jobs/created/$id'
    | '/api/public/hooks/sync-tick'
    | '/admin/dev/status/api'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/n3-launch'
    | '/settings'
    | '/support'
    | '/admin/dev'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/jobs/quick'
    | '/admin/dev/bootstrap'
    | '/admin/dev/n3-connect'
    | '/jobs'
    | '/admin/dev/status'
    | '/admin/dev/sync'
    | '/jobs/created/$id'
    | '/api/public/hooks/sync-tick'
    | '/admin/dev/status/api'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/n3-launch'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/admin/dev'
    | '/_authenticated/jobs/$jobId'
    | '/_authenticated/jobs/new'
    | '/_authenticated/jobs/quick'
    | '/admin/dev/bootstrap'
    | '/admin/dev/n3-connect'
    | '/_authenticated/jobs/'
    | '/_authenticated/admin/dev/status'
    | '/_authenticated/admin/dev/sync'
    | '/_authenticated/jobs/created/$id'
    | '/api/public/hooks/sync-tick'
    | '/_authenticated/admin/dev/status/api'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  N3LaunchRoute: typeof N3LaunchRoute
  AdminDevBootstrapRoute: typeof AdminDevBootstrapRoute
  AdminDevN3ConnectRoute: typeof AdminDevN3ConnectRoute
  ApiPublicHooksSyncTickRoute: typeof ApiPublicHooksSyncTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/n3-launch': {
      id: '/n3-launch'
      path: '/n3-launch'
      fullPath: '/n3-launch'
      preLoaderRoute: typeof N3LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/dev/n3-connect': {
      id: '/admin/dev/n3-connect'
      path: '/admin/dev/n3-connect'
      fullPath: '/admin/dev/n3-connect'
      preLoaderRoute: typeof AdminDevN3ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dev/bootstrap': {
      id: '/admin/dev/bootstrap'
      path: '/admin/dev/bootstrap'
      fullPath: '/admin/dev/bootstrap'
      preLoaderRoute: typeof AdminDevBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/jobs/quick': {
      id: '/_authenticated/jobs/quick'
      path: '/jobs/quick'
      fullPath: '/jobs/quick'
      preLoaderRoute: typeof AuthenticatedJobsQuickRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/new': {
      id: '/_authenticated/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthenticatedJobsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$jobId': {
      id: '/_authenticated/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dev': {
      id: '/_authenticated/admin/dev'
      path: '/admin/dev'
      fullPath: '/admin/dev'
      preLoaderRoute: typeof AuthenticatedAdminDevRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/sync-tick': {
      id: '/api/public/hooks/sync-tick'
      path: '/api/public/hooks/sync-tick'
      fullPath: '/api/public/hooks/sync-tick'
      preLoaderRoute: typeof ApiPublicHooksSyncTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/jobs/created/$id': {
      id: '/_authenticated/jobs/created/$id'
      path: '/jobs/created/$id'
      fullPath: '/jobs/created/$id'
      preLoaderRoute: typeof AuthenticatedJobsCreatedIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dev/sync': {
      id: '/_authenticated/admin/dev/sync'
      path: '/sync'
      fullPath: '/admin/dev/sync'
      preLoaderRoute: typeof AuthenticatedAdminDevSyncRouteImport
      parentRoute: typeof AuthenticatedAdminDevRouteRoute
    }
    '/_authenticated/admin/dev/status': {
      id: '/_authenticated/admin/dev/status'
      path: '/status'
      fullPath: '/admin/dev/status'
      preLoaderRoute: typeof AuthenticatedAdminDevStatusRouteImport
      parentRoute: typeof AuthenticatedAdminDevRouteRoute
    }
    '/_authenticated/admin/dev/status/api': {
      id: '/_authenticated/admin/dev/status/api'
      path: '/api'
      fullPath: '/admin/dev/status/api'
      preLoaderRoute: typeof AuthenticatedAdminDevStatusApiRouteImport
      parentRoute: typeof AuthenticatedAdminDevStatusRoute
    }
  }
}

interface AuthenticatedAdminDevStatusRouteChildren {
  AuthenticatedAdminDevStatusApiRoute: typeof AuthenticatedAdminDevStatusApiRoute
}

const AuthenticatedAdminDevStatusRouteChildren: AuthenticatedAdminDevStatusRouteChildren =
  {
    AuthenticatedAdminDevStatusApiRoute: AuthenticatedAdminDevStatusApiRoute,
  }

const AuthenticatedAdminDevStatusRouteWithChildren =
  AuthenticatedAdminDevStatusRoute._addFileChildren(
    AuthenticatedAdminDevStatusRouteChildren,
  )

interface AuthenticatedAdminDevRouteRouteChildren {
  AuthenticatedAdminDevStatusRoute: typeof AuthenticatedAdminDevStatusRouteWithChildren
  AuthenticatedAdminDevSyncRoute: typeof AuthenticatedAdminDevSyncRoute
}

const AuthenticatedAdminDevRouteRouteChildren: AuthenticatedAdminDevRouteRouteChildren =
  {
    AuthenticatedAdminDevStatusRoute:
      AuthenticatedAdminDevStatusRouteWithChildren,
    AuthenticatedAdminDevSyncRoute: AuthenticatedAdminDevSyncRoute,
  }

const AuthenticatedAdminDevRouteRouteWithChildren =
  AuthenticatedAdminDevRouteRoute._addFileChildren(
    AuthenticatedAdminDevRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedAdminDevRouteRoute: typeof AuthenticatedAdminDevRouteRouteWithChildren
  AuthenticatedJobsJobIdRoute: typeof AuthenticatedJobsJobIdRoute
  AuthenticatedJobsNewRoute: typeof AuthenticatedJobsNewRoute
  AuthenticatedJobsQuickRoute: typeof AuthenticatedJobsQuickRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
  AuthenticatedJobsCreatedIdRoute: typeof AuthenticatedJobsCreatedIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedAdminDevRouteRoute: AuthenticatedAdminDevRouteRouteWithChildren,
  AuthenticatedJobsJobIdRoute: AuthenticatedJobsJobIdRoute,
  AuthenticatedJobsNewRoute: AuthenticatedJobsNewRoute,
  AuthenticatedJobsQuickRoute: AuthenticatedJobsQuickRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
  AuthenticatedJobsCreatedIdRoute: AuthenticatedJobsCreatedIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  N3LaunchRoute: N3LaunchRoute,
  AdminDevBootstrapRoute: AdminDevBootstrapRoute,
  AdminDevN3ConnectRoute: AdminDevN3ConnectRoute,
  ApiPublicHooksSyncTickRoute: ApiPublicHooksSyncTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
