/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as N3LaunchRouteImport } from './routes/n3-launch'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatusApiRouteImport } from './routes/status.api'
import { Route as AdminBootstrapRouteImport } from './routes/admin.bootstrap'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs.index'
import { Route as AuthenticatedJobsQuickRouteImport } from './routes/_authenticated/jobs.quick'
import { Route as AuthenticatedJobsNewRouteImport } from './routes/_authenticated/jobs.new'
import { Route as AuthenticatedJobsJobIdRouteImport } from './routes/_authenticated/jobs.$jobId'
import { Route as AuthenticatedAdminSyncRouteImport } from './routes/_authenticated/admin/sync'
import { Route as ApiPublicHooksSyncTickRouteImport } from './routes/api/public/hooks/sync-tick'
import { Route as AuthenticatedJobsCreatedIdRouteImport } from './routes/_authenticated/jobs.created.$id'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const N3LaunchRoute = N3LaunchRouteImport.update({
  id: '/n3-launch',
  path: '/n3-launch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusApiRoute = StatusApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => StatusRoute,
} as any)
const AdminBootstrapRoute = AdminBootstrapRouteImport.update({
  id: '/admin/bootstrap',
  path: '/admin/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsQuickRoute = AuthenticatedJobsQuickRouteImport.update({
  id: '/jobs/quick',
  path: '/jobs/quick',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsNewRoute = AuthenticatedJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsJobIdRoute = AuthenticatedJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSyncRoute = AuthenticatedAdminSyncRouteImport.update({
  id: '/admin/sync',
  path: '/admin/sync',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksSyncTickRoute = ApiPublicHooksSyncTickRouteImport.update({
  id: '/api/public/hooks/sync-tick',
  path: '/api/public/hooks/sync-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJobsCreatedIdRoute =
  AuthenticatedJobsCreatedIdRouteImport.update({
    id: '/jobs/created/$id',
    path: '/jobs/created/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/n3-launch': typeof N3LaunchRoute
  '/status': typeof StatusRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/admin/bootstrap': typeof AdminBootstrapRoute
  '/status/api': typeof StatusApiRoute
  '/admin/sync': typeof AuthenticatedAdminSyncRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/jobs/quick': typeof AuthenticatedJobsQuickRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/jobs/created/$id': typeof AuthenticatedJobsCreatedIdRoute
  '/api/public/hooks/sync-tick': typeof ApiPublicHooksSyncTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/n3-launch': typeof N3LaunchRoute
  '/status': typeof StatusRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/admin/bootstrap': typeof AdminBootstrapRoute
  '/status/api': typeof StatusApiRoute
  '/admin/sync': typeof AuthenticatedAdminSyncRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/jobs/quick': typeof AuthenticatedJobsQuickRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/jobs/created/$id': typeof AuthenticatedJobsCreatedIdRoute
  '/api/public/hooks/sync-tick': typeof ApiPublicHooksSyncTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/n3-launch': typeof N3LaunchRoute
  '/status': typeof StatusRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/admin/bootstrap': typeof AdminBootstrapRoute
  '/status/api': typeof StatusApiRoute
  '/_authenticated/admin/sync': typeof AuthenticatedAdminSyncRoute
  '/_authenticated/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/_authenticated/jobs/new': typeof AuthenticatedJobsNewRoute
  '/_authenticated/jobs/quick': typeof AuthenticatedJobsQuickRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/jobs/created/$id': typeof AuthenticatedJobsCreatedIdRoute
  '/api/public/hooks/sync-tick': typeof ApiPublicHooksSyncTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/n3-launch'
    | '/status'
    | '/settings'
    | '/support'
    | '/admin/bootstrap'
    | '/status/api'
    | '/admin/sync'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/jobs/quick'
    | '/jobs/'
    | '/jobs/created/$id'
    | '/api/public/hooks/sync-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/n3-launch'
    | '/status'
    | '/settings'
    | '/support'
    | '/admin/bootstrap'
    | '/status/api'
    | '/admin/sync'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/jobs/quick'
    | '/jobs'
    | '/jobs/created/$id'
    | '/api/public/hooks/sync-tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/n3-launch'
    | '/status'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/admin/bootstrap'
    | '/status/api'
    | '/_authenticated/admin/sync'
    | '/_authenticated/jobs/$jobId'
    | '/_authenticated/jobs/new'
    | '/_authenticated/jobs/quick'
    | '/_authenticated/jobs/'
    | '/_authenticated/jobs/created/$id'
    | '/api/public/hooks/sync-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  N3LaunchRoute: typeof N3LaunchRoute
  StatusRoute: typeof StatusRouteWithChildren
  AdminBootstrapRoute: typeof AdminBootstrapRoute
  ApiPublicHooksSyncTickRoute: typeof ApiPublicHooksSyncTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n3-launch': {
      id: '/n3-launch'
      path: '/n3-launch'
      fullPath: '/n3-launch'
      preLoaderRoute: typeof N3LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/api': {
      id: '/status/api'
      path: '/api'
      fullPath: '/status/api'
      preLoaderRoute: typeof StatusApiRouteImport
      parentRoute: typeof StatusRoute
    }
    '/admin/bootstrap': {
      id: '/admin/bootstrap'
      path: '/admin/bootstrap'
      fullPath: '/admin/bootstrap'
      preLoaderRoute: typeof AdminBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/quick': {
      id: '/_authenticated/jobs/quick'
      path: '/jobs/quick'
      fullPath: '/jobs/quick'
      preLoaderRoute: typeof AuthenticatedJobsQuickRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/new': {
      id: '/_authenticated/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthenticatedJobsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$jobId': {
      id: '/_authenticated/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/sync': {
      id: '/_authenticated/admin/sync'
      path: '/admin/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof AuthenticatedAdminSyncRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/sync-tick': {
      id: '/api/public/hooks/sync-tick'
      path: '/api/public/hooks/sync-tick'
      fullPath: '/api/public/hooks/sync-tick'
      preLoaderRoute: typeof ApiPublicHooksSyncTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/jobs/created/$id': {
      id: '/_authenticated/jobs/created/$id'
      path: '/jobs/created/$id'
      fullPath: '/jobs/created/$id'
      preLoaderRoute: typeof AuthenticatedJobsCreatedIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedAdminSyncRoute: typeof AuthenticatedAdminSyncRoute
  AuthenticatedJobsJobIdRoute: typeof AuthenticatedJobsJobIdRoute
  AuthenticatedJobsNewRoute: typeof AuthenticatedJobsNewRoute
  AuthenticatedJobsQuickRoute: typeof AuthenticatedJobsQuickRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
  AuthenticatedJobsCreatedIdRoute: typeof AuthenticatedJobsCreatedIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedAdminSyncRoute: AuthenticatedAdminSyncRoute,
  AuthenticatedJobsJobIdRoute: AuthenticatedJobsJobIdRoute,
  AuthenticatedJobsNewRoute: AuthenticatedJobsNewRoute,
  AuthenticatedJobsQuickRoute: AuthenticatedJobsQuickRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
  AuthenticatedJobsCreatedIdRoute: AuthenticatedJobsCreatedIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface StatusRouteChildren {
  StatusApiRoute: typeof StatusApiRoute
}

const StatusRouteChildren: StatusRouteChildren = {
  StatusApiRoute: StatusApiRoute,
}

const StatusRouteWithChildren =
  StatusRoute._addFileChildren(StatusRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  N3LaunchRoute: N3LaunchRoute,
  StatusRoute: StatusRouteWithChildren,
  AdminBootstrapRoute: AdminBootstrapRoute,
  ApiPublicHooksSyncTickRoute: ApiPublicHooksSyncTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
